### ISSUE TITLE
Doesn't work with React 16

### ISSUE THREAD

**Issue by Trial-In-Error** [nkbt/react-debounce-input#107]
The underlying input's value changes, but the DebounceInput's value never changes. Changing debounce time didn't appear to affect behavior.

**Comment by nkbt** [comment]
It definitely works with react 16 pretty much since the release of react 16. Any more details? Codepen to reproduce your issue?

**Comment by Trial-In-Error** [comment]
Huh. Nothing as clean as a codepen, sadly. I noticed this while troubleshooting a bug using SwaggerUI 3 inside a React 16 application; remove the debouncedInput, and it starts working again. It's unfortunately quite a few steps to debug/reproduce in that full environment, and I don't have the time to pare it down to a minimal testcase. The swaggerUI pull request is [here](https://github.com/swagger-api/swagger-ui/pull/4982).

**Comment by nkbt** [comment]
As you can observe https://codepen.io/nkbt/pen/VvmzLQ?editors=0010 it certainly works with the latest react no issues. The problem is with the code you have around it.
If you do not have enough time to make a reproducible test case, I cannot help you anymore, as I cannot spend infinite amount of time guessing what the problem might be.
